### ISSUE TITLE
How this module go into effect?

### ISSUE THREAD

**Issue by luochen1990** [nodejs/full-icu-npm#13]
I find that the full-icu module is not required, node will work correctly if the icu data file (`icudt58l.dat`) is found by nodejs, no matter whether `require("full-icu")` is given.  I think this should be explained somewhere since it is not a normal useage of a npm module.

**Comment by srl295** [comment]
@luochen1990 this module is just to automatically load the data file. It is *not* always called `icudt58l.dat` but depends on your platform and endianness.  It might be icudt58b or icudt58e or icudt59l etc.

**Comment by srl295** [comment]
handle on #68
