### ISSUE TITLE
Unable to start with --icu-data-dir=node_modules\full-icu node v8 using with NVM

### ISSUE THREAD

**Issue by edgeineer** [nodejs/full-icu-npm#28]
node: could not initialize ICU (check NODE_ICU_DATA or --icu-data-dir parameters)                                                                                                                                                                                                

this happens when I use nodejs version 8  installed with nvm (node version manager) I am not able to start with full-icu

my process.versions is
{ http_parser: '2.8.0',
  node: '8.14.1',
  v8: '6.2.414.75',
  uv: '1.23.2',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  nghttp2: '1.33.0',
  napi: '3',
  openssl: '1.0.2q',
  icu: '60.1',
  unicode: '10.0',
  cldr: '32.0',
  tz: '2017c' }

But when I uninstall nvm and just install nodejs v8 the process.versions.icu is 62.1 and it works fine..
Only having this trouble starting with node v8 installed from nvm

**Comment by thedamon** [comment]
I'm having a trouble as well that's similar. I'm using yarn and nvm and I'm not sure what exactly the issue is, but i never had any trouble until I updated my node version using nvm and since then i haven't been able to get by my commit hook that needs full-icu...

**Comment by Taylor123** [comment]
Having the same issue. Did y'all find any solution to this?

**Comment by srl295** [comment]
Sorry to not respond earlier.

> EDIT: for me the issue was lint-staged via husky running a different version of node than the one i had set in nvm

try re-installing `full-icu`, it does sound like you may have a different node version than when you orriginally installed `full-icu`. It's not really a module, more of a installer loader

**Comment by thedamon** [comment]
I think that ended up getting it working. We ended up removing full_icu and the i18n stuff from our unit tests because some dev’s setups would constantly cause problems in our git hooks. Hopefully we’ll get proper CI Soon and we can run it on a server reliably
