### ISSUE TITLE
Pull from icu4c github release instead of package

### ISSUE THREAD

**Issue by srl295** [nodejs/full-icu-npm#36]
See [ICU-20600](https://unicode-org.atlassian.net/browse/ICU-20600) for the ICU side. Consider pulling the little endian data directly from the ICU src file (`https://github.com/unicode-org/icu/releases/download/release-64-2/icu4c-64_2-src.tgz`). BE and EBCDIC could pull from an adjunct data file also published by ICU.  This would break the dependency on the manual step of (me) remembering to upload the ICU data.

This also would make sure the dot-release issue mentioned in #35 does not occur, because fetching would be specific to the ICU dot release.

Also, `npm install` in postinstall is a bad idea, as https://github.com/unicode-org/full-icu-npm/issues/38 points out.

**Comment by srl295** [comment]
- Downside: unable to leverage npm package caching, proxies, etc.    However, ICU releases are on github (with its CDN) instead of a single icu-project server these days.

- Upside: is no more manually having to publish packages to icu4c-data@latest for each ICU release. 

- Other Upside: is to no longer have this odd package that installs another package, breaking dependency analysis and the package install model in general.

**Comment by srl295** [comment]
If it's not a package, this functionality (the fetch) could move into core… into `configure.py`… into the node installer (check this box to download full ICU)…?

**Comment by richardlau** [comment]
Sounds good. Will this just be for future versions of ICU or will the data files be retroactively published by the ICU project?

**Comment by srl295** [comment]
@richardlau maybe retroactively publish for current ICU 64.2 — that's going to be what Node LTS v10  uses soon enough. But not all versions.  Actually, for little endian non-EBCDIC, the data file is already in the .src.tgz and so several versions back are already available.

**Comment by caub** [comment]
What should we do with this https://github.com/unicode-org/icu/releases/download/release-64-2/icu4c-64_2-src.tgz? should it be saved/uncompressed in a specific directory?

**Comment by srl295** [comment]
> https://github.com/unicode-org/icu/releases/download/release-64-2/icu4c-64_2-src.tgz

If you're on little endian, then pull out `icu/source/data/in/icudt*l.dat` from that zip and copy it to a directory specified in `NODE_ICU_DATA` (env variable) or `--icu-data-dir=…` (node parameter) … see https://github.com/nodejs/node/blob/master/doc/api/intl.md#providing-icu-data-at-runtime

if you're on big endian you need to build ICU and convert the data.

> recently it stopped working

can you clarify? what stopped working?

**Comment by caub** [comment]
Oh sorry, it's working
```
docker run --rm node:slim bash -c "npm i full-icu; NODE_ICU_DATA='node_modules/full-icu' node -p 'new Intl.DateTimeFormat(\"fr-FR\", {dateStyle:\"full\"}).format(new Date())'"
```
`vendredi 30 août 2019`

thanks, nvm

**Comment by srl295** [comment]
in light of https://github.com/nodejs/node/pull/29522 I think ICU4C 65.1 is a good cutover time to start this new approach. This means no more updates to the icu4c-data repo.

**Comment by srl295** [comment]
- started on this https://github.com/unicode-org/full-icu-npm/tree/pull-l-from-gh

**Comment by ex1st** [comment]
Hello @srl295 
> in light of [nodejs/node#29522](https://github.com/nodejs/node/pull/29522) I think ICU4C 65.1 is a good cutover time to start this new approach. This means no more updates to the icu4c-data repo.

I think, need for at least one time more - #46
Thank you!

**Comment by ex1st** [comment]
@srl295 I've tried `npm i unicode-org/full-icu-npm#pull-l-from-gh` on v12.16.2, but got:

```
Error: EACCES: permission denied, mkdtemp '/tmpXXXXXX'
    at Object.mkdtempSync (fs.js:1773:3)
    at ClientRequest.<anonymous> (/home/user/work/node_modules/full-icu/myFetch.js:32:29)
    at Object.onceWrapper (events.js:417:26)
    at ClientRequest.emit (events.js:310:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:603:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:476:22)
    at TLSSocket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9) {
  errno: -13,
  syscall: 'mkdtemp',
  code: 'EACCES',
  path: '/tmpXXXXXX'
}
```

**Comment by srl295** [comment]
@ex1st Sorry, not done yet. I'll get back to work on it! 
( I didn't know about `npm i … #`!

**Comment by srl295** [comment]
@ilya I’ll have to pick this up Monday. Meanwhile if you go to
site.icu-project.org you will find that the icu4c source .zip and .tar
contain the icudt*l.dat file under Icu/source/data/in

**Comment by srl295** [comment]
@ex1st nevermind, i'm uploading it now

**Comment by srl295** [comment]
please note that ICU 67 RC is the first to 'natively' include the new -l and -b data packages, see https://github.com/unicode-org/icu/releases/tag/release-67-rc

**Comment by zen0wu** [comment]
Bump bump. Was just bitten by this today. `npm install` twice changes package-lock.json and invalidates all our node_modules cache. 🙏 🙏

**Comment by lukeundtrug** [comment]
Hi there, just a friendly bump on this promising topic as the current Node updates seem to be missing their respective ICU-data (68l) which led to issues when installing on Node > v14.15.

See #61 for reference 👍

**Comment by srl295** [comment]
Literally years in the making , PTAL https://github.com/nodejs/full-icu-npm/pull/53
