### ISSUE TITLE
Install process is broken/unsafe

### ISSUE THREAD

**Issue by grantila** [nodejs/full-icu-npm#38]
You can't yarn install (or npm install) in a postinstall script. It's not safe.
Yarn e.g. is unsafe to use (when hitting its cache, such as install, add, upgrade, ...) concurrently. Yarn runs multiple postinstall scripts in parallel, and if multiple packages do 'yarn install', the cache (hence packages) can become corrupt.

I've gotten around this by wrapping yarn and adding a host-level mutex around it, but then I can't install anything that depends on full-icu.

Consider a different approach.

Plus, you're bypassing yarn's/npm's own dependency graph optimization/flattening.

**Comment by srl295** [comment]
see #36 for another approach

**Comment by srl295** [comment]
Fixed in #53 by no longer doing npm install
