### ISSUE TITLE
Can't install with pnpm or yarn v2

### ISSUE THREAD

**Issue by donaldpipowitch** [nodejs/full-icu-npm#44]
If you try to install `full-icu` with pnpm or yarn v2 you'll get errors. pnpm v4 seems to freeze and yarn v2 shows _"Unexpected string" at full-icu/install-spawn.js._ The problem seems to be this line: https://github.com/unicode-org/full-icu-npm/blob/master/install-spawn.js#L62

**Comment by TrySound** [comment]
Here's an answer from yarn maintainer
https://github.com/yarnpkg/berry/issues/873#issuecomment-591346241

**Comment by srl295** [comment]
@donaldpipowitch hi, sounds like yarn v2 needs to be detected specially (how?)

**Comment by andrioid** [comment]
Experiencing this with yarn 1.19.1 as well.

**Comment by 3dos** [comment]
Hello, bumping on this issue. I tried to find a solution to this problem myself but couldn't figure a workaround. Has anyone found anything?

**Comment by srl295** [comment]
> Hello, bumping on this issue. I tried to find a solution to this problem myself but couldn't figure a workaround. Has anyone found anything?

Sorry I haven't got a chance to look into this myself, an answer on how to detect yarn v2 could help. ￼

**Comment by srl295** [comment]
in any event, https://github.com/unicode-org/full-icu-npm/pull/53 should fix it assuming i get around to it
