### ISSUE TITLE
Can't specify ICU data version to install

### ISSUE THREAD

**Issue by iansu** [nodejs/full-icu-npm#60]
As far as I can tell this package just pulls the latest version of the ICU data when you install it. Something changed in a recent ICU data release which has broken some of my code. It would be really nice if there was some way to specify which version of the ICU data you wanted to install.

**Comment by srl295** [comment]
It doesn't pull the latest, it pulls the exact binary version that matches the Icu version in your node binary. If there's something broken please file a node bug and you can mention me and this issue.

**Comment by iansu** [comment]
https://github.com/nodejs/node/issues/38897

**Comment by srl295** [comment]
> nodejs/node#38897

Ah yes, we've already dialogued there and I have replied some.

In any event, full-icu _could_ have a utility that takes a version that would override `process.versions.icu` but I'm not sure how useful that would really be.

**Comment by srl295** [comment]
@iansu need more clarification
