### ISSUE TITLE
Full-icu tries to install a version of icu4c-data (68l) that doesn't exist

### ISSUE THREAD

**Issue by lukeundtrug** [nodejs/full-icu-npm#61]
Hi there,

it seems I'm encountering a bug where in our CI pipeline full-icu tries to install a version of icu4c-data that does not exist. When trying to install this version locally I get the same error as shown in the screenshot. Does anybody encounter the same problem? 

![image](https://user-images.githubusercontent.com/26152379/121694852-cd35ed00-caca-11eb-8099-b0925a3643a6.png)

**Comment by lukeundtrug** [comment]
It seems that there just isn't a package up on npm for v.68.2/68l yet as can be seen [here](https://www.npmjs.com/package/icu4c-data):
![image](https://user-images.githubusercontent.com/26152379/121856085-61cf6380-ccf4-11eb-8b67-388bca83b63f.png)

A rollback to Node v14.15.0 fixed the issue for us as the corresponding ICU version for that is 67l for which a tag does exist 👍

**Comment by marcwittke** [comment]
my Fedora with nodejs 14.17.0 already requires `69l`

```
npm install icu4c-data@69l (Node 16.5.0 and small-icu 69.1) -> icudt69l.dat
Looks like you are using yarn…
full-icu$ /usr/bin/node /usr/lib/node_modules/yarn/bin/yarn.js add icu4c-data@69l --no-lockfile --ignore-scripts
yarn add v1.22.10
info No lockfile found.
[1/4] Resolving packages...
error Couldn't find any versions for "icu4c-data" that matches "69l"
```

solved it for now by downgrading to 14.16.0: `dnf install nodejs-14.16.0`

**Comment by santiago-perez-altran** [comment]
Same problem here with the latest Node LTS version 14.17.5. No matching version found for icu4c-data@69l.

`````
2 verbose stack icu4c-data: No matching version found for icu4c-data@69l.
12 verbose stack     at pickManifest (/Users/ekojo/.nvm/versions/node/v14.17.5/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:122:13)
12 verbose stack     at /Users/ekojo/.nvm/versions/node/v14.17.5/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:24:14
12 verbose stack     at tryCatcher (/Users/ekojo/.nvm/versions/node/v14.17.5/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
12 verbose stack     at Promise._settlePromiseFromHandler (/Users/ekojo/.nvm/versions/node/v14.17.5/lib/node_modules/npm/node_modules/bluebird/js/rel
```````

**Comment by santiago-perez-altran** [comment]
Same problem here with the latest Node LTS version 14.17.5.

`````
12 verbose stack icu4c-data: No matching version found for icu4c-data@69l.
``````

**Comment by LyraelRayne** [comment]
@srl295 any chance you could rescue us the way you did in #46 ?

**Comment by srl295** [comment]
I'd really rather get help with #53, that would solve this permanently￼

**Comment by srl295** [comment]
Try #53 it fixes this

**Comment by srl295** [comment]
- post install considered harmful by yarn: https://yarnpkg.com/advanced/lifecycle-scripts#a-note-about-postinstall
 -

**Comment by marcwittke** [comment]
fwiw: node 16+ includes full-icu by default, so we removed it from our package.json and the error went away

https://nodejs.org/docs/latest-v16.x/api/intl.html#embed-the-entire-icu-full-icu

`--with-intl=full-icu` (default)

**Comment by srl295** [comment]
@marcwittke yes, although removal should not be _necessary_:

- if full icu data is built into node, then the `full-icu` module doesn't do anything (harmless)

- if you upgrade to the latest `full-icu` without a later node, the download should succeed.

But of course it's fine to remove a module you will no longer need.

**Comment by johnnygreen** [comment]
hi ... 
the env i'm in has node v18 with small-icu, completely locked down / using private npm reg. 
its trying to download the file from gh, no go.
tried to use `FULL_ICU_PREFER_NPM=1` ... results in npm download failing with icu4c-data@731 404

requesting team to change my env to full-icu ... but would be nice for the npm package to exist.

**Comment by srl295** [comment]
@johnnygreen i assume gh is locked down somehow... sorry, i don't think i can add the packages.  

perhaps you could follow https://github.com/nodejs/icu4c-data-npm and make your own package? you can use the API in full-icu to verify that you have the right datafile.
